/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentWithDefinitionsDtoAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentWithDefinitionsDtoAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentWithDefinitionsDtoAllOf
        //private DeploymentWithDefinitionsDtoAllOf instance;

        public DeploymentWithDefinitionsDtoAllOfTests()
        {
            // TODO uncomment below to create an instance of DeploymentWithDefinitionsDtoAllOf
            //instance = new DeploymentWithDefinitionsDtoAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentWithDefinitionsDtoAllOf
        /// </summary>
        [Fact]
        public void DeploymentWithDefinitionsDtoAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentWithDefinitionsDtoAllOf
            //Assert.IsType<DeploymentWithDefinitionsDtoAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'DeployedProcessDefinitions'
        /// </summary>
        [Fact]
        public void DeployedProcessDefinitionsTest()
        {
            // TODO unit test for the property 'DeployedProcessDefinitions'
        }
        /// <summary>
        /// Test the property 'DeployedDecisionDefinitions'
        /// </summary>
        [Fact]
        public void DeployedDecisionDefinitionsTest()
        {
            // TODO unit test for the property 'DeployedDecisionDefinitions'
        }
        /// <summary>
        /// Test the property 'DeployedDecisionRequirementsDefinitions'
        /// </summary>
        [Fact]
        public void DeployedDecisionRequirementsDefinitionsTest()
        {
            // TODO unit test for the property 'DeployedDecisionRequirementsDefinitions'
        }
        /// <summary>
        /// Test the property 'DeployedCaseDefinitions'
        /// </summary>
        [Fact]
        public void DeployedCaseDefinitionsTest()
        {
            // TODO unit test for the property 'DeployedCaseDefinitions'
        }

    }

}
