/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EvaluationConditionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvaluationConditionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvaluationConditionDto
        //private EvaluationConditionDto instance;

        public EvaluationConditionDtoTests()
        {
            // TODO uncomment below to create an instance of EvaluationConditionDto
            //instance = new EvaluationConditionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvaluationConditionDto
        /// </summary>
        [Fact]
        public void EvaluationConditionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EvaluationConditionDto
            //Assert.IsType<EvaluationConditionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Fact]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'WithoutTenantId'
        /// </summary>
        [Fact]
        public void WithoutTenantIdTest()
        {
            // TODO unit test for the property 'WithoutTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }

    }

}
