/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FetchExternalTaskTopicDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FetchExternalTaskTopicDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FetchExternalTaskTopicDto
        //private FetchExternalTaskTopicDto instance;

        public FetchExternalTaskTopicDtoTests()
        {
            // TODO uncomment below to create an instance of FetchExternalTaskTopicDto
            //instance = new FetchExternalTaskTopicDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FetchExternalTaskTopicDto
        /// </summary>
        [Fact]
        public void FetchExternalTaskTopicDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FetchExternalTaskTopicDto
            //Assert.IsType<FetchExternalTaskTopicDto>(instance);
        }


        /// <summary>
        /// Test the property 'TopicName'
        /// </summary>
        [Fact]
        public void TopicNameTest()
        {
            // TODO unit test for the property 'TopicName'
        }
        /// <summary>
        /// Test the property 'LockDuration'
        /// </summary>
        [Fact]
        public void LockDurationTest()
        {
            // TODO unit test for the property 'LockDuration'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'LocalVariables'
        /// </summary>
        [Fact]
        public void LocalVariablesTest()
        {
            // TODO unit test for the property 'LocalVariables'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Fact]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionIdIn'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdInTest()
        {
            // TODO unit test for the property 'ProcessDefinitionIdIn'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Fact]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKeyIn'
        /// </summary>
        [Fact]
        public void ProcessDefinitionKeyInTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKeyIn'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionVersionTag'
        /// </summary>
        [Fact]
        public void ProcessDefinitionVersionTagTest()
        {
            // TODO unit test for the property 'ProcessDefinitionVersionTag'
        }
        /// <summary>
        /// Test the property 'WithoutTenantId'
        /// </summary>
        [Fact]
        public void WithoutTenantIdTest()
        {
            // TODO unit test for the property 'WithoutTenantId'
        }
        /// <summary>
        /// Test the property 'TenantIdIn'
        /// </summary>
        [Fact]
        public void TenantIdInTest()
        {
            // TODO unit test for the property 'TenantIdIn'
        }
        /// <summary>
        /// Test the property 'ProcessVariables'
        /// </summary>
        [Fact]
        public void ProcessVariablesTest()
        {
            // TODO unit test for the property 'ProcessVariables'
        }
        /// <summary>
        /// Test the property 'DeserializeValues'
        /// </summary>
        [Fact]
        public void DeserializeValuesTest()
        {
            // TODO unit test for the property 'DeserializeValues'
        }
        /// <summary>
        /// Test the property 'IncludeExtensionProperties'
        /// </summary>
        [Fact]
        public void IncludeExtensionPropertiesTest()
        {
            // TODO unit test for the property 'IncludeExtensionProperties'
        }

    }

}
