/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessInstanceSuspensionStateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessInstanceSuspensionStateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceSuspensionStateDto
        //private ProcessInstanceSuspensionStateDto instance;

        public ProcessInstanceSuspensionStateDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessInstanceSuspensionStateDto
            //instance = new ProcessInstanceSuspensionStateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessInstanceSuspensionStateDto
        /// </summary>
        [Fact]
        public void ProcessInstanceSuspensionStateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessInstanceSuspensionStateDto
            //Assert.IsType<ProcessInstanceSuspensionStateDto>(instance);
        }


        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Fact]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Fact]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionTenantId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionTenantIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionWithoutTenantId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionWithoutTenantIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionWithoutTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceIds'
        /// </summary>
        [Fact]
        public void ProcessInstanceIdsTest()
        {
            // TODO unit test for the property 'ProcessInstanceIds'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceQuery'
        /// </summary>
        [Fact]
        public void ProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'ProcessInstanceQuery'
        }
        /// <summary>
        /// Test the property 'HistoricProcessInstanceQuery'
        /// </summary>
        [Fact]
        public void HistoricProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'HistoricProcessInstanceQuery'
        }

    }

}
