/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessDefinitionDiagramDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessDefinitionDiagramDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionDiagramDto
        //private ProcessDefinitionDiagramDto instance;

        public ProcessDefinitionDiagramDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionDiagramDto
            //instance = new ProcessDefinitionDiagramDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessDefinitionDiagramDto
        /// </summary>
        [Fact]
        public void ProcessDefinitionDiagramDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessDefinitionDiagramDto
            //Assert.IsType<ProcessDefinitionDiagramDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Bpmn20Xml'
        /// </summary>
        [Fact]
        public void Bpmn20XmlTest()
        {
            // TODO unit test for the property 'Bpmn20Xml'
        }

    }

}
