/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessInstanceDtoAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessInstanceDtoAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceDtoAllOf
        //private ProcessInstanceDtoAllOf instance;

        public ProcessInstanceDtoAllOfTests()
        {
            // TODO uncomment below to create an instance of ProcessInstanceDtoAllOf
            //instance = new ProcessInstanceDtoAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessInstanceDtoAllOf
        /// </summary>
        [Fact]
        public void ProcessInstanceDtoAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessInstanceDtoAllOf
            //Assert.IsType<ProcessInstanceDtoAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DefinitionId'
        /// </summary>
        [Fact]
        public void DefinitionIdTest()
        {
            // TODO unit test for the property 'DefinitionId'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Fact]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'CaseInstanceId'
        /// </summary>
        [Fact]
        public void CaseInstanceIdTest()
        {
            // TODO unit test for the property 'CaseInstanceId'
        }
        /// <summary>
        /// Test the property 'Ended'
        /// </summary>
        [Fact]
        public void EndedTest()
        {
            // TODO unit test for the property 'Ended'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Fact]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

    }

}
