/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.OpenApi.Client.Api;
using Camunda.OpenApi.Client.Model;
using Camunda.OpenApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.OpenApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RestartProcessInstanceModificationInstructionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestartProcessInstanceModificationInstructionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestartProcessInstanceModificationInstructionDto
        //private RestartProcessInstanceModificationInstructionDto instance;

        public RestartProcessInstanceModificationInstructionDtoTests()
        {
            // TODO uncomment below to create an instance of RestartProcessInstanceModificationInstructionDto
            //instance = new RestartProcessInstanceModificationInstructionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestartProcessInstanceModificationInstructionDto
        /// </summary>
        [Fact]
        public void RestartProcessInstanceModificationInstructionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestartProcessInstanceModificationInstructionDto
            //Assert.IsType<RestartProcessInstanceModificationInstructionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'TransitionId'
        /// </summary>
        [Fact]
        public void TransitionIdTest()
        {
            // TODO unit test for the property 'TransitionId'
        }

    }

}
