/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CamundaClient.Client;
using CamundaClient.Api;
// uncomment below to import models
//using CamundaClient.Model;

namespace CamundaClient.Test.Api
{
    /// <summary>
    ///  Class for testing TaskIdentityLinkApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TaskIdentityLinkApiTests : IDisposable
    {
        private TaskIdentityLinkApi instance;

        public TaskIdentityLinkApiTests()
        {
            instance = new TaskIdentityLinkApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskIdentityLinkApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TaskIdentityLinkApi
            //Assert.IsType<TaskIdentityLinkApi>(instance);
        }

        /// <summary>
        /// Test AddIdentityLink
        /// </summary>
        [Fact]
        public void AddIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto identityLinkDto = null;
            //instance.AddIdentityLink(id, identityLinkDto);
        }

        /// <summary>
        /// Test DeleteIdentityLink
        /// </summary>
        [Fact]
        public void DeleteIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto identityLinkDto = null;
            //instance.DeleteIdentityLink(id, identityLinkDto);
        }

        /// <summary>
        /// Test GetIdentityLinks
        /// </summary>
        [Fact]
        public void GetIdentityLinksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string type = null;
            //var response = instance.GetIdentityLinks(id, type);
            //Assert.IsType<List<IdentityLinkDto>>(response);
        }
    }
}
