/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ActivityInstanceIncidentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityInstanceIncidentDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivityInstanceIncidentDto
        //private ActivityInstanceIncidentDto instance;

        public ActivityInstanceIncidentDtoTests()
        {
            // TODO uncomment below to create an instance of ActivityInstanceIncidentDto
            //instance = new ActivityInstanceIncidentDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivityInstanceIncidentDto
        /// </summary>
        [Fact]
        public void ActivityInstanceIncidentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivityInstanceIncidentDto
            //Assert.IsType<ActivityInstanceIncidentDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ParentActivityInstanceId'
        /// </summary>
        [Fact]
        public void ParentActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ParentActivityInstanceId'
        }

    }

}
