/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing CountResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CountResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CountResultDto
        //private CountResultDto instance;

        public CountResultDtoTests()
        {
            // TODO uncomment below to create an instance of CountResultDto
            //instance = new CountResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountResultDto
        /// </summary>
        [Fact]
        public void CountResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CountResultDto
            //Assert.IsType<CountResultDto>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

    }

}
