/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing EventSubscriptionQueryDtoSorting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventSubscriptionQueryDtoSortingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventSubscriptionQueryDtoSorting
        //private EventSubscriptionQueryDtoSorting instance;

        public EventSubscriptionQueryDtoSortingTests()
        {
            // TODO uncomment below to create an instance of EventSubscriptionQueryDtoSorting
            //instance = new EventSubscriptionQueryDtoSorting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventSubscriptionQueryDtoSorting
        /// </summary>
        [Fact]
        public void EventSubscriptionQueryDtoSortingInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventSubscriptionQueryDtoSorting
            //Assert.IsType<EventSubscriptionQueryDtoSorting>(instance);
        }


        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Fact]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
