/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ExtendLockOnExternalTaskDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtendLockOnExternalTaskDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtendLockOnExternalTaskDto
        //private ExtendLockOnExternalTaskDto instance;

        public ExtendLockOnExternalTaskDtoTests()
        {
            // TODO uncomment below to create an instance of ExtendLockOnExternalTaskDto
            //instance = new ExtendLockOnExternalTaskDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtendLockOnExternalTaskDto
        /// </summary>
        [Fact]
        public void ExtendLockOnExternalTaskDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtendLockOnExternalTaskDto
            //Assert.IsType<ExtendLockOnExternalTaskDto>(instance);
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'NewDuration'
        /// </summary>
        [Fact]
        public void NewDurationTest()
        {
            // TODO unit test for the property 'NewDuration'
        }

    }

}
