/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalTaskFailureDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalTaskFailureDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalTaskFailureDto
        //private ExternalTaskFailureDto instance;

        public ExternalTaskFailureDtoTests()
        {
            // TODO uncomment below to create an instance of ExternalTaskFailureDto
            //instance = new ExternalTaskFailureDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalTaskFailureDto
        /// </summary>
        [Fact]
        public void ExternalTaskFailureDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalTaskFailureDto
            //Assert.IsType<ExternalTaskFailureDto>(instance);
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Fact]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Fact]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'RetryTimeout'
        /// </summary>
        [Fact]
        public void RetryTimeoutTest()
        {
            // TODO unit test for the property 'RetryTimeout'
        }

    }

}
