/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalTaskBpmnErrorAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalTaskBpmnErrorAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalTaskBpmnErrorAllOf
        //private ExternalTaskBpmnErrorAllOf instance;

        public ExternalTaskBpmnErrorAllOfTests()
        {
            // TODO uncomment below to create an instance of ExternalTaskBpmnErrorAllOf
            //instance = new ExternalTaskBpmnErrorAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalTaskBpmnErrorAllOf
        /// </summary>
        [Fact]
        public void ExternalTaskBpmnErrorAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalTaskBpmnErrorAllOf
            //Assert.IsType<ExternalTaskBpmnErrorAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }

    }

}
