/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing FetchExternalTasksDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FetchExternalTasksDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FetchExternalTasksDto
        //private FetchExternalTasksDto instance;

        public FetchExternalTasksDtoTests()
        {
            // TODO uncomment below to create an instance of FetchExternalTasksDto
            //instance = new FetchExternalTasksDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FetchExternalTasksDto
        /// </summary>
        [Fact]
        public void FetchExternalTasksDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FetchExternalTasksDto
            //Assert.IsType<FetchExternalTasksDto>(instance);
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'MaxTasks'
        /// </summary>
        [Fact]
        public void MaxTasksTest()
        {
            // TODO unit test for the property 'MaxTasks'
        }
        /// <summary>
        /// Test the property 'UsePriority'
        /// </summary>
        [Fact]
        public void UsePriorityTest()
        {
            // TODO unit test for the property 'UsePriority'
        }
        /// <summary>
        /// Test the property 'AsyncResponseTimeout'
        /// </summary>
        [Fact]
        public void AsyncResponseTimeoutTest()
        {
            // TODO unit test for the property 'AsyncResponseTimeout'
        }
        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }

    }

}
