/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing FormDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FormDto
        //private FormDto instance;

        public FormDtoTests()
        {
            // TODO uncomment below to create an instance of FormDto
            //instance = new FormDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FormDto
        /// </summary>
        [Fact]
        public void FormDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FormDto
            //Assert.IsType<FormDto>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'ContextPath'
        /// </summary>
        [Fact]
        public void ContextPathTest()
        {
            // TODO unit test for the property 'ContextPath'
        }

    }

}
