/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing HistoricActivityInstanceQueryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistoricActivityInstanceQueryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistoricActivityInstanceQueryDto
        //private HistoricActivityInstanceQueryDto instance;

        public HistoricActivityInstanceQueryDtoTests()
        {
            // TODO uncomment below to create an instance of HistoricActivityInstanceQueryDto
            //instance = new HistoricActivityInstanceQueryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistoricActivityInstanceQueryDto
        /// </summary>
        [Fact]
        public void HistoricActivityInstanceQueryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistoricActivityInstanceQueryDto
            //Assert.IsType<HistoricActivityInstanceQueryDto>(instance);
        }


        /// <summary>
        /// Test the property 'ActivityInstanceId'
        /// </summary>
        [Fact]
        public void ActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ActivityInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Fact]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Fact]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'ActivityName'
        /// </summary>
        [Fact]
        public void ActivityNameTest()
        {
            // TODO unit test for the property 'ActivityName'
        }
        /// <summary>
        /// Test the property 'ActivityType'
        /// </summary>
        [Fact]
        public void ActivityTypeTest()
        {
            // TODO unit test for the property 'ActivityType'
        }
        /// <summary>
        /// Test the property 'TaskAssignee'
        /// </summary>
        [Fact]
        public void TaskAssigneeTest()
        {
            // TODO unit test for the property 'TaskAssignee'
        }
        /// <summary>
        /// Test the property 'Finished'
        /// </summary>
        [Fact]
        public void FinishedTest()
        {
            // TODO unit test for the property 'Finished'
        }
        /// <summary>
        /// Test the property 'Unfinished'
        /// </summary>
        [Fact]
        public void UnfinishedTest()
        {
            // TODO unit test for the property 'Unfinished'
        }
        /// <summary>
        /// Test the property 'Canceled'
        /// </summary>
        [Fact]
        public void CanceledTest()
        {
            // TODO unit test for the property 'Canceled'
        }
        /// <summary>
        /// Test the property 'CompleteScope'
        /// </summary>
        [Fact]
        public void CompleteScopeTest()
        {
            // TODO unit test for the property 'CompleteScope'
        }
        /// <summary>
        /// Test the property 'StartedBefore'
        /// </summary>
        [Fact]
        public void StartedBeforeTest()
        {
            // TODO unit test for the property 'StartedBefore'
        }
        /// <summary>
        /// Test the property 'StartedAfter'
        /// </summary>
        [Fact]
        public void StartedAfterTest()
        {
            // TODO unit test for the property 'StartedAfter'
        }
        /// <summary>
        /// Test the property 'FinishedBefore'
        /// </summary>
        [Fact]
        public void FinishedBeforeTest()
        {
            // TODO unit test for the property 'FinishedBefore'
        }
        /// <summary>
        /// Test the property 'FinishedAfter'
        /// </summary>
        [Fact]
        public void FinishedAfterTest()
        {
            // TODO unit test for the property 'FinishedAfter'
        }
        /// <summary>
        /// Test the property 'TenantIdIn'
        /// </summary>
        [Fact]
        public void TenantIdInTest()
        {
            // TODO unit test for the property 'TenantIdIn'
        }
        /// <summary>
        /// Test the property 'WithoutTenantId'
        /// </summary>
        [Fact]
        public void WithoutTenantIdTest()
        {
            // TODO unit test for the property 'WithoutTenantId'
        }
        /// <summary>
        /// Test the property 'Sorting'
        /// </summary>
        [Fact]
        public void SortingTest()
        {
            // TODO unit test for the property 'Sorting'
        }

    }

}
