/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing PriorityDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriorityDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriorityDto
        //private PriorityDto instance;

        public PriorityDtoTests()
        {
            // TODO uncomment below to create an instance of PriorityDto
            //instance = new PriorityDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriorityDto
        /// </summary>
        [Fact]
        public void PriorityDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriorityDto
            //Assert.IsType<PriorityDto>(instance);
        }


        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

    }

}
