/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessInstanceModificationInstructionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessInstanceModificationInstructionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceModificationInstructionDto
        //private ProcessInstanceModificationInstructionDto instance;

        public ProcessInstanceModificationInstructionDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessInstanceModificationInstructionDto
            //instance = new ProcessInstanceModificationInstructionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessInstanceModificationInstructionDto
        /// </summary>
        [Fact]
        public void ProcessInstanceModificationInstructionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessInstanceModificationInstructionDto
            //Assert.IsType<ProcessInstanceModificationInstructionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'TransitionId'
        /// </summary>
        [Fact]
        public void TransitionIdTest()
        {
            // TODO unit test for the property 'TransitionId'
        }
        /// <summary>
        /// Test the property 'ActivityInstanceId'
        /// </summary>
        [Fact]
        public void ActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ActivityInstanceId'
        }
        /// <summary>
        /// Test the property 'TransitionInstanceId'
        /// </summary>
        [Fact]
        public void TransitionInstanceIdTest()
        {
            // TODO unit test for the property 'TransitionInstanceId'
        }
        /// <summary>
        /// Test the property 'AncestorActivityInstanceId'
        /// </summary>
        [Fact]
        public void AncestorActivityInstanceIdTest()
        {
            // TODO unit test for the property 'AncestorActivityInstanceId'
        }
        /// <summary>
        /// Test the property 'CancelCurrentActiveActivityInstances'
        /// </summary>
        [Fact]
        public void CancelCurrentActiveActivityInstancesTest()
        {
            // TODO unit test for the property 'CancelCurrentActiveActivityInstances'
        }

    }

}
