/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessDefinitionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessDefinitionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionDto
        //private ProcessDefinitionDto instance;

        public ProcessDefinitionDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionDto
            //instance = new ProcessDefinitionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessDefinitionDto
        /// </summary>
        [Fact]
        public void ProcessDefinitionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessDefinitionDto
            //Assert.IsType<ProcessDefinitionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Fact]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }
        /// <summary>
        /// Test the property 'Diagram'
        /// </summary>
        [Fact]
        public void DiagramTest()
        {
            // TODO unit test for the property 'Diagram'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Fact]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'VersionTag'
        /// </summary>
        [Fact]
        public void VersionTagTest()
        {
            // TODO unit test for the property 'VersionTag'
        }
        /// <summary>
        /// Test the property 'HistoryTimeToLive'
        /// </summary>
        [Fact]
        public void HistoryTimeToLiveTest()
        {
            // TODO unit test for the property 'HistoryTimeToLive'
        }
        /// <summary>
        /// Test the property 'StartableInTasklist'
        /// </summary>
        [Fact]
        public void StartableInTasklistTest()
        {
            // TODO unit test for the property 'StartableInTasklist'
        }

    }

}
