/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessInstanceModificationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessInstanceModificationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceModificationDto
        //private ProcessInstanceModificationDto instance;

        public ProcessInstanceModificationDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessInstanceModificationDto
            //instance = new ProcessInstanceModificationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessInstanceModificationDto
        /// </summary>
        [Fact]
        public void ProcessInstanceModificationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessInstanceModificationDto
            //Assert.IsType<ProcessInstanceModificationDto>(instance);
        }


        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Fact]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Fact]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Fact]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Annotation'
        /// </summary>
        [Fact]
        public void AnnotationTest()
        {
            // TODO unit test for the property 'Annotation'
        }

    }

}
