/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessDefinitionStatisticsResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessDefinitionStatisticsResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionStatisticsResultDto
        //private ProcessDefinitionStatisticsResultDto instance;

        public ProcessDefinitionStatisticsResultDtoTests()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionStatisticsResultDto
            //instance = new ProcessDefinitionStatisticsResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessDefinitionStatisticsResultDto
        /// </summary>
        [Fact]
        public void ProcessDefinitionStatisticsResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessDefinitionStatisticsResultDto
            //Assert.IsType<ProcessDefinitionStatisticsResultDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Fact]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
        /// <summary>
        /// Test the property 'FailedJobs'
        /// </summary>
        [Fact]
        public void FailedJobsTest()
        {
            // TODO unit test for the property 'FailedJobs'
        }
        /// <summary>
        /// Test the property 'Incidents'
        /// </summary>
        [Fact]
        public void IncidentsTest()
        {
            // TODO unit test for the property 'Incidents'
        }
        /// <summary>
        /// Test the property 'Definition'
        /// </summary>
        [Fact]
        public void DefinitionTest()
        {
            // TODO unit test for the property 'Definition'
        }

    }

}
