/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceOptionsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceOptionsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceOptionsDto
        //private ResourceOptionsDto instance;

        public ResourceOptionsDtoTests()
        {
            // TODO uncomment below to create an instance of ResourceOptionsDto
            //instance = new ResourceOptionsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceOptionsDto
        /// </summary>
        [Fact]
        public void ResourceOptionsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceOptionsDto
            //Assert.IsType<ResourceOptionsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
