/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing TaskDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskDto
        //private TaskDto instance;

        public TaskDtoTests()
        {
            // TODO uncomment below to create an instance of TaskDto
            //instance = new TaskDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskDto
        /// </summary>
        [Fact]
        public void TaskDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskDto
            //Assert.IsType<TaskDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Due'
        /// </summary>
        [Fact]
        public void DueTest()
        {
            // TODO unit test for the property 'Due'
        }
        /// <summary>
        /// Test the property 'FollowUp'
        /// </summary>
        [Fact]
        public void FollowUpTest()
        {
            // TODO unit test for the property 'FollowUp'
        }
        /// <summary>
        /// Test the property 'DelegationState'
        /// </summary>
        [Fact]
        public void DelegationStateTest()
        {
            // TODO unit test for the property 'DelegationState'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Fact]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'ParentTaskId'
        /// </summary>
        [Fact]
        public void ParentTaskIdTest()
        {
            // TODO unit test for the property 'ParentTaskId'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Fact]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'CaseExecutionId'
        /// </summary>
        [Fact]
        public void CaseExecutionIdTest()
        {
            // TODO unit test for the property 'CaseExecutionId'
        }
        /// <summary>
        /// Test the property 'CaseDefinitionId'
        /// </summary>
        [Fact]
        public void CaseDefinitionIdTest()
        {
            // TODO unit test for the property 'CaseDefinitionId'
        }
        /// <summary>
        /// Test the property 'CaseInstanceId'
        /// </summary>
        [Fact]
        public void CaseInstanceIdTest()
        {
            // TODO unit test for the property 'CaseInstanceId'
        }
        /// <summary>
        /// Test the property 'TaskDefinitionKey'
        /// </summary>
        [Fact]
        public void TaskDefinitionKeyTest()
        {
            // TODO unit test for the property 'TaskDefinitionKey'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Fact]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Fact]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

    }

}
