/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CamundaClient.Api;
using CamundaClient.Model;
using CamundaClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CamundaClient.Test.Model
{
    /// <summary>
    ///  Class for testing TelemetryConfigurationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TelemetryConfigurationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TelemetryConfigurationDto
        //private TelemetryConfigurationDto instance;

        public TelemetryConfigurationDtoTests()
        {
            // TODO uncomment below to create an instance of TelemetryConfigurationDto
            //instance = new TelemetryConfigurationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TelemetryConfigurationDto
        /// </summary>
        [Fact]
        public void TelemetryConfigurationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TelemetryConfigurationDto
            //Assert.IsType<TelemetryConfigurationDto>(instance);
        }


        /// <summary>
        /// Test the property 'EnableTelemetry'
        /// </summary>
        [Fact]
        public void EnableTelemetryTest()
        {
            // TODO unit test for the property 'EnableTelemetry'
        }

    }

}
