/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CamundaClient.Client;
using CamundaClient.Model;

namespace CamundaClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        List<SchemaLogEntryDto> GetSchemaLog(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        ApiResponse<List<SchemaLogEntryDto>> GetSchemaLogWithHttpInfo(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        List<SchemaLogEntryDto> QuerySchemaLog(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        ApiResponse<List<SchemaLogEntryDto>> QuerySchemaLogWithHttpInfo(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        System.Threading.Tasks.Task<List<SchemaLogEntryDto>> GetSchemaLogAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SchemaLogEntryDto>>> GetSchemaLogWithHttpInfoAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        System.Threading.Tasks.Task<List<SchemaLogEntryDto>> QuerySchemaLogAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Queries for schema log entries that fulfill given parameters.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SchemaLogEntryDto>>> QuerySchemaLogWithHttpInfoAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchemaLogApi : ISchemaLogApiSync, ISchemaLogApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SchemaLogApi : ISchemaLogApi
    {
        private CamundaClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SchemaLogApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SchemaLogApi(String basePath)
        {
            this.Configuration = CamundaClient.Client.Configuration.MergeConfigurations(
                CamundaClient.Client.GlobalConfiguration.Instance,
                new CamundaClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SchemaLogApi(CamundaClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CamundaClient.Client.Configuration.MergeConfigurations(
                CamundaClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaLogApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SchemaLogApi(CamundaClient.Client.ISynchronousClient client, CamundaClient.Client.IAsynchronousClient asyncClient, CamundaClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CamundaClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CamundaClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CamundaClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CamundaClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        public List<SchemaLogEntryDto> GetSchemaLog(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = GetSchemaLogWithHttpInfo(version, firstResult, maxResults);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        public CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> GetSchemaLogWithHttpInfo(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?))
        {
            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<SchemaLogEntryDto>> GetSchemaLogAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = await GetSchemaLogWithHttpInfoAsync(version, firstResult, maxResults, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version">Only return schema log entries with a specific version. (optional)</param>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        public async System.Threading.Tasks.Task<CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>>> GetSchemaLogWithHttpInfoAsync(string version = default(string), int? firstResult = default(int?), int? maxResults = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }
            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>List&lt;SchemaLogEntryDto&gt;</returns>
        public List<SchemaLogEntryDto> QuerySchemaLog(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto))
        {
            CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = QuerySchemaLogWithHttpInfo(firstResult, maxResults, schemaLogQueryDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <returns>ApiResponse of List&lt;SchemaLogEntryDto&gt;</returns>
        public CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> QuerySchemaLogWithHttpInfo(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto))
        {
            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }
            localVarRequestOptions.Data = schemaLogQueryDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("QuerySchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchemaLogEntryDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<SchemaLogEntryDto>> QuerySchemaLogAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>> localVarResponse = await QuerySchemaLogWithHttpInfoAsync(firstResult, maxResults, schemaLogQueryDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Queries for schema log entries that fulfill given parameters.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="firstResult">Pagination of results. Specifies the index of the first result to return. (optional)</param>
        /// <param name="maxResults">Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)</param>
        /// <param name="schemaLogQueryDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchemaLogEntryDto&gt;)</returns>
        public async System.Threading.Tasks.Task<CamundaClient.Client.ApiResponse<List<SchemaLogEntryDto>>> QuerySchemaLogWithHttpInfoAsync(int? firstResult = default(int?), int? maxResults = default(int?), SchemaLogQueryDto schemaLogQueryDto = default(SchemaLogQueryDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (firstResult != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "firstResult", firstResult));
            }
            if (maxResults != null)
            {
                localVarRequestOptions.QueryParameters.Add(CamundaClient.Client.ClientUtils.ParameterToMultiMap("", "maxResults", maxResults));
            }
            localVarRequestOptions.Data = schemaLogQueryDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<SchemaLogEntryDto>>("/schema/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("QuerySchemaLog", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
