/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CamundaClient.Client;
using CamundaClient.Model;

namespace CamundaClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskCommentApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a comment for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <returns>CommentDto</returns>
        CommentDto CreateComment(string id, CommentDto commentDto = default(CommentDto));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a comment for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <returns>ApiResponse of CommentDto</returns>
        ApiResponse<CommentDto> CreateCommentWithHttpInfo(string id, CommentDto commentDto = default(CommentDto));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieves a task comment by task id and comment id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <returns>CommentDto</returns>
        CommentDto GetComment(string id, string commentId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieves a task comment by task id and comment id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <returns>ApiResponse of CommentDto</returns>
        ApiResponse<CommentDto> GetCommentWithHttpInfo(string id, string commentId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Gets the comments for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <returns>List&lt;CommentDto&gt;</returns>
        List<CommentDto> GetComments(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Gets the comments for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <returns>ApiResponse of List&lt;CommentDto&gt;</returns>
        ApiResponse<List<CommentDto>> GetCommentsWithHttpInfo(string id);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskCommentApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a comment for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommentDto</returns>
        System.Threading.Tasks.Task<CommentDto> CreateCommentAsync(string id, CommentDto commentDto = default(CommentDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a comment for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommentDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CommentDto>> CreateCommentWithHttpInfoAsync(string id, CommentDto commentDto = default(CommentDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieves a task comment by task id and comment id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommentDto</returns>
        System.Threading.Tasks.Task<CommentDto> GetCommentAsync(string id, string commentId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieves a task comment by task id and comment id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommentDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CommentDto>> GetCommentWithHttpInfoAsync(string id, string commentId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Gets the comments for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CommentDto&gt;</returns>
        System.Threading.Tasks.Task<List<CommentDto>> GetCommentsAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Gets the comments for a task by id.
        /// </remarks>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CommentDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CommentDto>>> GetCommentsWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaskCommentApi : ITaskCommentApiSync, ITaskCommentApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TaskCommentApi : ITaskCommentApi
    {
        private CamundaClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskCommentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaskCommentApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskCommentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaskCommentApi(String basePath)
        {
            this.Configuration = CamundaClient.Client.Configuration.MergeConfigurations(
                CamundaClient.Client.GlobalConfiguration.Instance,
                new CamundaClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskCommentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TaskCommentApi(CamundaClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CamundaClient.Client.Configuration.MergeConfigurations(
                CamundaClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CamundaClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskCommentApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TaskCommentApi(CamundaClient.Client.ISynchronousClient client, CamundaClient.Client.IAsynchronousClient asyncClient, CamundaClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CamundaClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CamundaClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CamundaClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CamundaClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CamundaClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Creates a comment for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <returns>CommentDto</returns>
        public CommentDto CreateComment(string id, CommentDto commentDto = default(CommentDto))
        {
            CamundaClient.Client.ApiResponse<CommentDto> localVarResponse = CreateCommentWithHttpInfo(id, commentDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a comment for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <returns>ApiResponse of CommentDto</returns>
        public CamundaClient.Client.ApiResponse<CommentDto> CreateCommentWithHttpInfo(string id, CommentDto commentDto = default(CommentDto))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->CreateComment");

            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = commentDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<CommentDto>("/task/{id}/comment/create", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateComment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates a comment for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommentDto</returns>
        public async System.Threading.Tasks.Task<CommentDto> CreateCommentAsync(string id, CommentDto commentDto = default(CommentDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CamundaClient.Client.ApiResponse<CommentDto> localVarResponse = await CreateCommentWithHttpInfoAsync(id, commentDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a comment for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to add the comment to.</param>
        /// <param name="commentDto">**Note:** Only the &#x60;message&#x60; property will be used. Every other property passed to this endpoint will be ignored. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommentDto)</returns>
        public async System.Threading.Tasks.Task<CamundaClient.Client.ApiResponse<CommentDto>> CreateCommentWithHttpInfoAsync(string id, CommentDto commentDto = default(CommentDto), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->CreateComment");


            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = commentDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CommentDto>("/task/{id}/comment/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateComment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Retrieves a task comment by task id and comment id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <returns>CommentDto</returns>
        public CommentDto GetComment(string id, string commentId)
        {
            CamundaClient.Client.ApiResponse<CommentDto> localVarResponse = GetCommentWithHttpInfo(id, commentId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieves a task comment by task id and comment id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <returns>ApiResponse of CommentDto</returns>
        public CamundaClient.Client.ApiResponse<CommentDto> GetCommentWithHttpInfo(string id, string commentId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->GetComment");

            // verify the required parameter 'commentId' is set
            if (commentId == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'commentId' when calling TaskCommentApi->GetComment");

            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("commentId", CamundaClient.Client.ClientUtils.ParameterToString(commentId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<CommentDto>("/task/{id}/comment/{commentId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetComment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Retrieves a task comment by task id and comment id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommentDto</returns>
        public async System.Threading.Tasks.Task<CommentDto> GetCommentAsync(string id, string commentId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CamundaClient.Client.ApiResponse<CommentDto> localVarResponse = await GetCommentWithHttpInfoAsync(id, commentId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieves a task comment by task id and comment id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task.</param>
        /// <param name="commentId">The id of the comment to be retrieved.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommentDto)</returns>
        public async System.Threading.Tasks.Task<CamundaClient.Client.ApiResponse<CommentDto>> GetCommentWithHttpInfoAsync(string id, string commentId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->GetComment");

            // verify the required parameter 'commentId' is set
            if (commentId == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'commentId' when calling TaskCommentApi->GetComment");


            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("commentId", CamundaClient.Client.ClientUtils.ParameterToString(commentId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CommentDto>("/task/{id}/comment/{commentId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetComment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Gets the comments for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <returns>List&lt;CommentDto&gt;</returns>
        public List<CommentDto> GetComments(string id)
        {
            CamundaClient.Client.ApiResponse<List<CommentDto>> localVarResponse = GetCommentsWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Gets the comments for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <returns>ApiResponse of List&lt;CommentDto&gt;</returns>
        public CamundaClient.Client.ApiResponse<List<CommentDto>> GetCommentsWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->GetComments");

            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CommentDto>>("/task/{id}/comment", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetComments", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Gets the comments for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CommentDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<CommentDto>> GetCommentsAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CamundaClient.Client.ApiResponse<List<CommentDto>> localVarResponse = await GetCommentsWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Gets the comments for a task by id.
        /// </summary>
        /// <exception cref="CamundaClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the task to retrieve the comments for.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CommentDto&gt;)</returns>
        public async System.Threading.Tasks.Task<CamundaClient.Client.ApiResponse<List<CommentDto>>> GetCommentsWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new CamundaClient.Client.ApiException(400, "Missing required parameter 'id' when calling TaskCommentApi->GetComments");


            CamundaClient.Client.RequestOptions localVarRequestOptions = new CamundaClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = CamundaClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CamundaClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CamundaClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<CommentDto>>("/task/{id}/comment", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetComments", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
